name: Build And Push Docker

on:
  workflow_call:
    inputs:
      repository-name:
        description: "Name of the DockerHub repository"
        required: true
        type: string
      image-tag:
        description: "Docker image tag"
        required: true
        type: string
      local-path:
        description: "Path to the directory containing Dockerfile"
        required: true
        type: string
      dockerhub-username:
        required: true
        type: string
      dockerhub-token:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR source branch
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ inputs.dockerhub-token }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ inputs.dockerhub-username }}/${{ inputs.repository-name }}:${{ inputs.image-tag }} ${{ inputs.local-path }}
          docker push ${{ inputs.dockerhub-username }}/${{ inputs.repository-name }}:${{ inputs.image-tag }}
