name: Build and Push .NET App

on:
  pull_request:
    branches:
      - main
    paths: ["DockerHubBackend/**"]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit hash
        id: extract_tag
        run: |
          echo "Tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: ./.github/workflows/build-and-push-docker.yml
        with:
          repository-name: uks-backend
          image-tag: ${{ steps.extract_tag.outputs.TAG }}
          local-path: ./DockerHubBackend/DockerHubBackend
