name: Build and Push .NET App

on:
  pull_request:
    branches:
      - main
    paths: ["DockerHubBackend/**"]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      repository-name: uks-backend
      image-tag: ${{ github.sha::7 }}
      local-path: ./DockerHubBackend/DockerHubBackend
