name: Build and Push Angular App

on:
  pull_request:
    branches:
      - main
    paths: ["front/**"]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: uks-frontend

    steps:
      - name: Checkout PR source branch (dev)
        uses: actions/checkout@v4
      - name: Get commit hash
        id: extract_tag
        run: |
          echo "Tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.TAG }} ./front
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.TAG }}
