name: Build and Push Angular App

on:
  pull_request:
    branches:
      - main
    paths: ["front/**"]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      repository-name: uks-frontend
      image-tag: ${{ github.sha.substring(0, 7) }}
      local-path: ./front