name: Build and Push .NET App (Release Version)

on:
  push:
    tags:
      - "backend-v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4    
      - name: Build and push Docker image
        uses: ./.github/workflows/build-and-push-docker.yml
        with:
          repository-name: uks-backend
          image-tag: ${{ github.ref_name }}
          local-path: ./DockerHubBackend/DockerHubBackend